### PR TITLE
Fix cursor position in server url

### LINKED ISSUE #377: Fix "Server url" field in "Connection" dialog
After typing anything not at the end of a text, "Server url" field in Connection Dialog moves cursor to the end pos. It's very hard to type something in the middle of already written text.

### PR DESCRIPTION
**Pull request by boryspoplawski**
Fixes #377

### CODE REVIEW

File: src/ui/dialogs/connectiondialog.cc [hunk 1]
```diff
@@ -100,7 +100,16 @@ ConnectionDialog::ConnectionDialog(QWidget* parent)
   connect(ui_->server_url_line_edit, &QLineEdit::textEdited,
           [this](const QString& text) {
             QString trimmed_text = text.trimmed();
+            int pos = ui_->server_url_line_edit->cursorPosition();
+
+            if (0 < trimmed_text.length()) {
```
Comment (mkow) [inline src/ui/dialogs/connectiondialog.cc]: https://en.wikipedia.org/wiki/Yoda_conditions
