### PR TITLE
Fix networking

### LINKED ISSUE #316: OSX client cannot connect on fresh install
Appears to be an issue with SSL (which is default) for connecting to localhost server:

Trying to start a new server...
    working directory: /Applications/veles.app/Contents/Resources/veles-server
    python script name: srv.py
    python interpreter executable: /Applications/veles.app/Contents/MacOS/../Resources/veles-server/venv/bin/python3
    arguments:
        srv.py
        --cert-dir
        /Users/user/Library/Application Support/Codisec/Veles
        veles+ssl://@127.0.0.1:3135
        /Users/user/Library/Application Support/Codisec/Veles/veles.vdb

Waiting for a new server to start...
Process of locally created server started.
INFO:root:Świtezianka server is starting up...
INFO:root:Opening database...
INFO:root:Loading plugins...
INFO:root:Starting SSL server...
NetworkClient::connect
    client interface: 127.0.0.1
    server host: 127.0.0.1
    server port: 3135
NetworkClient: bind successful.
NetworkClient: New connection status: Connecting.
INFO:veles.server.proto:Client url: VELES+SSL://:476C9D1E89AD56029E382904F33CAA72C8A4FC7F3F9CF53228618D5B892B0F26@127.0.0.1:3135
INFO:root:Ready.
NetworkClient: unexpected error: The root CA certificate is not trusted for this purpose
NetworkClient: New connection status: Not Connected.
NetworkClient: Socket error - The host name did not match any of the valid hosts for this certificate
NetworkClient: TCP socket disconnected.

Disabling SSL in the Connect menu, and reconnecting twice seems to work.

### PR DESCRIPTION
**Pull request by mkow**
Fixes #316.

* Fixes certificate error on macOS (#316)
* Disallows valid SSL certificates with non-matching fingerprint
* Fixes a random unrelated issue in Python code (I'm too lazy to do a separate PR from this, sorry :P )

I have much more changes for networking code locally, but let's merge this fix for now.

### CODE REVIEW

File: src/client/networkclient.cc [hunk 1]
```diff
@@ -168,9 +168,9 @@ void NetworkClient::connect(const QString& server_url,
 
     // TODO(altran01): Why is bind causing a problem here?
     // if (client_socket_->bind(QHostAddress(client_interface_name))) {
-    if (output() != nullptr) {
+    /*if (output() != nullptr) {
```
Comment (koriakin) [inline src/client/networkclient.cc]: Do kasacji.
